using UnityEngine;

// Plays a sound for each game event. Any clip left empty in the Inspector is generated by SfxSynth,
// so a real audio file can replace a synthesised sound just by dragging it into the slot.
[RequireComponent(typeof(AudioSource))]
public class AudioManager : MonoBehaviour
{
    [SerializeField] [Range(0f, 1f)] private float _volume = 0.6f;

    [Header("Clips (optional)")]
    [SerializeField] private AudioClip _launch;
    [SerializeField] private AudioClip _blast;
    [SerializeField] private AudioClip _kill;
    [SerializeField] private AudioClip _impact;
    [SerializeField] private AudioClip _cityLost;
    [SerializeField] private AudioClip _waveStart;
    [SerializeField] private AudioClip _gameOver;

    private AudioSource _source;

    private void Awake()
    {
        _source = GetComponent<AudioSource>();
        FillMissingClips();
    }

    private void OnEnable()
    {
        Battery.Fired += PlayLaunch;
        Blast.Detonated += PlayBlast;
        Meteor.Destroyed += PlayKill;
        Meteor.Impacted += PlayImpact;
        City.Destroyed += PlayCityLost;
        WaveSpawner.WaveStarted += PlayWaveStart;
        GameManager.GameOver += PlayGameOver;
    }

    private void OnDisable()
    {
        Battery.Fired -= PlayLaunch;
        Blast.Detonated -= PlayBlast;
        Meteor.Destroyed -= PlayKill;
        Meteor.Impacted -= PlayImpact;
        City.Destroyed -= PlayCityLost;
        WaveSpawner.WaveStarted -= PlayWaveStart;
        GameManager.GameOver -= PlayGameOver;
    }

    private void FillMissingClips()
    {
        _launch = _launch != null ? _launch : SfxSynth.Launch();
        _blast = _blast != null ? _blast : SfxSynth.Blast();
        _kill = _kill != null ? _kill : SfxSynth.Kill();
        _impact = _impact != null ? _impact : SfxSynth.Impact();
        _cityLost = _cityLost != null ? _cityLost : SfxSynth.CityLost();
        _waveStart = _waveStart != null ? _waveStart : SfxSynth.WaveStart();
        _gameOver = _gameOver != null ? _gameOver : SfxSynth.GameOver();
    }

    private void Play(AudioClip clip)
    {
        _source.PlayOneShot(clip, _volume);
    }

    private void PlayLaunch()
    {
        Play(_launch);
    }

    private void PlayBlast()
    {
        Play(_blast);
    }

    private void PlayKill()
    {
        Play(_kill);
    }

    private void PlayImpact()
    {
        Play(_impact);
    }

    private void PlayCityLost()
    {
        Play(_cityLost);
    }

    private void PlayWaveStart(int wave)
    {
        Play(_waveStart);
    }

    private void PlayGameOver()
    {
        Play(_gameOver);
    }
}
